### ISSUE TITLE
通知の条件が違う疑惑

### ISSUE THREAD

**Issue by asSqr** [yuhi-sa/Atcoder-day1#1]
間違っていたら申し訳ないのですが test.py で全員が AC のものを集めているところの条件は == AC ではないですか？

**Comment by asSqr** [comment]
というか、少なくとも一人が AC しているものを最後に差集合をとっているように見えました

**Comment by yuhi-sa** [comment]
間違ってましたー！
ありがとうございます．

**Comment by asSqr** [comment]
返信遅れました！ よかったです！ (フォローしてもらったの反映されていない？🤔)

**Comment by yuhi-sa** [comment]
A=誰か1人がACしている問題の集合
B=指定した色の問題の集合
C=A-B
  =だれもACされてない指定色の問題
になってない、、ですかね、、？

**Comment by asSqr** [comment]
すみません，立て込んでて返信遅れましたが，解決しましたか？ 上のコメントは C = B-A な気がしていて，差集合は B-A = B \cap A^c だと思っているので行けるんじゃないかなあと思いました

**Comment by yuhi-sa** [comment]
なるほど．
実行結果見てる感じ多分いけてると思います．
